// Code generated by xrpc. DO NOT EDIT.
package main

import "github.com/yc90s/xrpc"
import "github.com/yc90s/xrpc/examples/protobuf/pb"


type IHelloService interface {
    Hello(*pb.String) (*pb.String, error)
    Add(*pb.String, *pb.String) (*pb.String, error)
}

func RegisterHelloServiceServer(rpc *xrpc.RPCServer, s IHelloService) {
    rpc.Register("Hello", s.Hello)
    rpc.Register("Add", s.Add)
}

type HelloServiceClient struct {
    *xrpc.RPCClient
}

func NewHelloServiceClient(c *xrpc.RPCClient) *HelloServiceClient {
    return &HelloServiceClient{c}
}

func (c *HelloServiceClient) Hello(subj string, arg0 *pb.String) (*pb.String, error) {
    var reply pb.String
    err := c.Call(subj, "Hello", &reply, arg0)
    return &reply, err
}
func (c *HelloServiceClient) Add(subj string, arg0 *pb.String, arg1 *pb.String) (*pb.String, error) {
    var reply pb.String
    err := c.Call(subj, "Add", &reply, arg0, arg1)
    return &reply, err
}